apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-component8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-component8
    app.kubernetes.io/part-of: e2e-fbc-application7
  name: e2e-fbc-component8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: e2e-fbc-component8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: e2e-fbc-component8
    spec:
      containers:
      - image: quay.io/qijing/dev-release-team-tenant/e2e-fbc-application7/e2e-fbc-component8@sha256:2d1f20e2f81a73fa2630db7603261420463631d3eb05250fe07b22424b590a16
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
