apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-fbc-component8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-fbc-component8
    app.kubernetes.io/part-of: e2e-fbc-application7
  name: e2e-fbc-component8
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: e2e-fbc-component8
status:
  loadBalancer: {}
